### ISSUE TITLE
http-forwarder doesn't compile with typescript version 3.6.x

### ISSUE THREAD

**Issue by Yannic92** [bosch-io/iot-things-examples#33]
### Versions used
NPM: 6.4.1
NodeJs: v10.5.3
typescript: 3.6.3

### What is happening
```
$ tsc
../../../home/user/.nvm/versions/node/v10.15.3/lib/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.
41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~
  node_modules/@types/node/index.d.ts:73:11
    73 interface IteratorResult<T> { }
                 ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.
node_modules/@types/node/index.d.ts:73:11 - error TS2300: Duplicate identifier 'IteratorResult'.
73 interface IteratorResult<T> { }
             ~~~~~~~~~~~~~~
  ../../../home/user/.nvm/versions/node/v10.15.3/lib/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

Found 2 errors.
```

### What should happen

When running `tsc` a successful build is expected.

**Comment by ghandim** [comment]
This is now part or Bosch IoT Things. Please have a look at https://docs.bosch-iot-suite.com/things/getting-started/booking/manage-y-connection/.
